// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_WQ-9Hiq_QayoSPW32PD_dm_wxjmif5w',
    appId: '1:988669472202:web:231edb579ee159b2413333',
    messagingSenderId: '988669472202',
    projectId: 'software-lab-test',
    authDomain: 'software-lab-test.firebaseapp.com',
    storageBucket: 'software-lab-test.firebasestorage.app',
    measurementId: 'G-XYXP8Q3YH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjwwnaM1iKdry3EKZ11sUnz7TYFL8ivE0',
    appId: '1:988669472202:android:fa0681c7571b448e413333',
    messagingSenderId: '988669472202',
    projectId: 'software-lab-test',
    storageBucket: 'software-lab-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqHtC9ALiVAZy4SYwTf9PM7N_XzZF9NI0',
    appId: '1:988669472202:ios:4ed6aef051944a79413333',
    messagingSenderId: '988669472202',
    projectId: 'software-lab-test',
    storageBucket: 'software-lab-test.firebasestorage.app',
    iosBundleId: 'com.example.softwareLabTask',
  );
}
